name       : unpaper
version    : 6.1
release    : 2
source     :
    - https://github.com/Flameeyes/unpaper/archive/unpaper-6.1.tar.gz : 213f8143b3361dde3286537eb66aaf7cdd7e4f5e7bde42ac6e91020997a81f1d
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : unpaper is a post-processing tool for scanned sheets of paper
description: |
    unpaper is a post-processing tool for scanned sheets of paper, especially for book pages that have been scanned from previously created photocopies. The main purpose is to make scanned book pages better readable on screen after conversion to PDF.
builddeps  :
    - docbook-xml
    - pkgconfig(libavcodec)
setup      : |
    %patch -p1 < $pkgfiles/fix_ffmpeg_incompatibility.patch
    %reconfigure
build      : |
    %make MANPAGE_XSL=/usr/share/xml/docbook/xsl-stylesheets-1.79.2/manpages/docbook.xsl
install    : |
    %make_install
